WebApp.Composite/Models/AppIdentityDbContext.cs
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using WebApp.Composite.Models;

namespace BaseProject.Models
{
    public class AppIdentityDbContext : IdentityDbContext<AppUser>
    {
        public AppIdentityDbContext(DbContextOptions<AppIdentityDbContext> options) : base(options)
        {

        }
        public DbSet<Book> Books { get; set; }
        public DbSet<Category> Categories { get; set; }
       
    }
}

WebApp.Composite/Models/AppUser.cs
using Microsoft.AspNetCore.Identity;

namespace BaseProject.Models
{
    public class AppUser : IdentityUser
    {
       
    }
}

WebApp.Composite/Models/Book.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace WebApp.Composite.Models
{
    public class Book
    {
        public int Id { get; set; }
        public string Name { get; set; }
        [ForeignKey("CategoryId")]
        public Category Category { get; set; }
        public int CategoryId { get; set; }
    }
}

WebApp.Composite/Models/Category.cs
using System.Collections.Generic;

namespace WebApp.Composite.Models
{
    public class Category
    {
        //Id Name      UserId ReferenceId //Üst kategoriyi tutuyor 0 ise üst kategorisi yok.
        //1 kitaplar    1        0 
        //2 kitaplar1   1        1    
        public int Id { get; set; }
        public string Name { get; set; }
        public string UserId { get; set; }

        public ICollection<Book> Books { get; set; }
        public int ReferenceId { get; set; }

    }
}

WebApp.Composite/Models/ErrorViewModel.cs
using System;

namespace BaseProject.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApp.Composite/Controllers/AccountController.cs
using BaseProject.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace BaseProject.Controllers
{
    public class AccountController : Controller
    {
        private readonly UserManager<AppUser> _userManager;
        private readonly SignInManager<AppUser> _signInManager;

        public AccountController(UserManager<AppUser> userManager,SignInManager<AppUser> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(string email,string password)
        {
            var hasUser = await _userManager.FindByEmailAsync(email);

            if (hasUser == null) return View();

            var signInResult = await _signInManager.PasswordSignInAsync(hasUser, password, true, false);

            if (!signInResult.Succeeded)
            {
                return View();
            }
            //Nameof kullanarak HomeControllerdaki ismi değişse bile nameof sayesinde bize hata dönmez.
            return RedirectToAction(nameof(HomeController.Index), "Home");
        }

        public async Task<IActionResult> LogOut()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction(nameof(HomeController.Index), "Home");
        }

    }
}

WebApp.Composite/Controllers/CategoryMenuController.cs
using BaseProject.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using WebApp.Composite.Composite;
using WebApp.Composite.Models;

namespace WebApp.Composite.Controllers
{
    [Authorize]
    public class CategoryMenuController : Controller
    {
        private readonly AppIdentityDbContext _context;

        public CategoryMenuController(AppIdentityDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            //category => bookcomposite;
            //book => bookcomponent

            //Cookiden çekebiliriz

            var userId = User.Claims.First(x => x.Type == ClaimTypes.NameIdentifier).Value;

            var categories = await _context.Categories.Include(x => x.Books)
                .Where(x => x.UserId == userId)
                .OrderBy(x => x.Id).ToListAsync();

            //Buradaki Category veritabanı Category için kök, BookComposite ise composite için kök
            var menu = GetMenus(categories,new Category { Name="TopCategory",Id=0},new BookComposite(0,"TopMenu"));

            ViewBag.menu = menu;

            ViewBag.selectList = menu.Components.SelectMany(x => ((BookComposite)x).GetSelectListItems(""));

            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Index(int categoryId,string bookName)
        {
            await _context.Books.AddAsync(new Book { CategoryId = categoryId, Name = bookName });
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        public BookComposite GetMenus(List<Category> categories,Category topCategory,
            BookComposite topBookComposite,BookComposite last=null)
        {
            //Her bir categoriden bir bookComposite her bir Book tanda bir Component oluşturacağaz

            categories.Where(x => x.ReferenceId == topCategory.Id).ToList().ForEach(categoryItem =>
              {
                  var bookComposite = new BookComposite(categoryItem.Id,categoryItem.Name);
                  categoryItem.Books.ToList().ForEach(bookItem =>
                  {
                      bookComposite.Add(new BookComponent(bookItem.Id,bookItem.Name));

                  });

                  if(last != null)
                  {
                      last.Add(bookComposite);
                  }
                  else
                  {
                      topBookComposite.Add(bookComposite);
                  }


                  GetMenus(categories,categoryItem,topBookComposite,bookComposite);


              });

            return topBookComposite;
        }

    }
}

WebApp.Composite/Controllers/HomeController.cs
using BaseProject.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace BaseProject.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApp.Composite/Views/CategoryMenu/Index.cshtml
@{
    ViewData["Title"] = "Index";
    var menu =ViewBag.menu as BookComposite;
}
<form asp-controller="CategoryMenu" asp-action="Index" method="post">
  
    <select asp-items="ViewBag.selectList"></select>
    <input type="text" name="bookName" />
    <input type="submit" value="Save"/>
</form>


<div class="row mt-5">
    <div class="col-md-4">

        <div class="card bg-light">

            <div class="card-header">
                Toplam Kitap(@menu.Count())
            </div>
            <div class="card-body">
                @foreach (var item in menu.Components)
               {
                   @Html.Raw(item.Display())
               }
            </div>
        </div>

    </div>




</div>

WebApp.Composite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BaseProject</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BaseProject</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CategoryMenu" asp-action="Index">Category Page</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <a asp-controller="Account" asp-action="LogOut" class="nav-link text-dark">@User.Identity.Name (Çıkış Yap)</a>
                        }
                        else
                        {
                            <a asp-controller="Account" asp-action="Login" class="nav-link text-dark">@User.Identity.Name Giriş Yap</a>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - BaseProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>